### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by otargowski** [MikolajKolek/toster#52] opened 2024-12-04 16:10 UTC
`rustup 1.27.1 (2024-05-07)`, `cargo 1.83.0 (5ffbef321 2024-10-29)`.
Got the following error when trying to build `master` with `cargo build`:

```
error[E0308]: mismatched types
   --> src/test_summary.rs:122:68
    |
122 |             if self.slowest_test.is_none_or(|(time, _)| new_time > time) {
    |                                                                    ^^^^ expected `&Duration`, found `Duration`
    |
help: consider dereferencing the borrow
    |
122 |             if self.slowest_test.is_none_or(|(time, _)| *new_time > time) {
    |                                                         +

error[E0308]: mismatched types
   --> src/test_summary.rs:128:76
    |
128 |             if self.most_memory_used.is_none_or(|(memory, _)| new_memory > memory) {
    |                                                                            ^^^^^^ expected `&u64`, found `u64`
    |
help: consider dereferencing the borrow
    |
128 |             if self.most_memory_used.is_none_or(|(memory, _)| *new_memory > memory) {
    |                                                               +
```

The change suggested above doesn't work, though then another suggestion (provided below) is made, which does work.
I have absolutely no idea whether this is correct or horrible, as I don't know rust at all:
```
diff --git a/src/test_summary.rs b/src/test_summary.rs
index c0c402c..3125ad8 100644
--- a/src/test_summary.rs
+++ b/src/test_summary.rs
@@ -118,15 +118,15 @@ impl TestSummary {
     }
 
     fn add_metrics(&mut self, metrics: &ExecutionMetrics, test_name: &str) {
-        if let Some(new_time) = &metrics.time {
-            if self.slowest_test.is_none_or(|(time, _)| new_time > time) {
-                self.slowest_test = Some((*new_time, test_name.to_string()));
+        if let Some(new_time) = metrics.time {
+            if self.slowest_test.as_mut().is_none_or(|(time, _)| new_time > *time) {
+                self.slowest_test = Some((new_time, test_name.to_string()));
             }
         }
 
-        if let Some(new_memory) = &metrics.memory_kibibytes {
-            if self.most_memory_used.is_none_or(|(memory, _)| new_memory > memory) {
-                self.most_memory_used = Some((*new_memory, test_name.to_string()));
+        if let Some(new_memory) = metrics.memory_kibibytes {
+            if self.most_memory_used.as_mut().is_none_or(|(memory, _)| new_memory > *memory) {
+                self.most_memory_used = Some((new_memory, test_name.to_string()));
             }
         }
     }
```

**Comment by MikolajKolek** [comment] 2024-12-04 16:44
This error seems to be caused by Rust 1.82 adding a utility method with the same name as a method we add to `Option`, but with slightly different functionality. I'll make sure to fix this on master by the end of the week, and in the meantime it looks like your fix would work.

Additionally, I have to warn you that currently master is not totally stable, as it's the version following a total rewrite and it hasn't been properly tested or finished yet. No releases of this version have been made as of yet (even if I'm planning to do so, I just have little time for it at this moment). If you want a more stable experience, I recommend the [1.2.2](https://github.com/MikolajKolek/toster/tree/1.2.2) branch

**Comment by MikolajKolek** [comment] 2024-12-06 23:04
Fixed in [the newest commit](https://github.com/MikolajKolek/toster/commit/90b0b2981d58baead0906a6baa8be8443484f504).

**Closed by MikolajKolek** 2024-12-06 23:04 UTC
Labels: bug
